apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: servicio-api-m2pf
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/project-mlops9-cm-streamlit/repo-mlops9-m2pf/image-v14-servicio-m2pf-datapath:latest
          env:
          ports:
            - containerPort: 4006