steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'us-central1-docker.pkg.dev/project-mlops9-cm/repo-mlops9-m2pf/image-v7-servicio-fastapi-m2pf-datapath:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/project-mlops9-cm/repo-mlops9-m2pf/image-v7-servicio-fastapi-m2pf-datapath:latest']